### ISSUE TITLE
RBAC plugin and service to service auth

### ISSUE THREAD

**Issue by boris154** [janus-idp/backstage-plugins#1248]
Hi,

I have a general question about implementing the RBAC plugin.

My setup of backstage includes the service to service authentication described [here](https://backstage.io/docs/auth/service-to-service-auth/).

While adding the RBAC plugin, I noticed that the plugin sends a request to `.well-known/backstage/permissions/metadata` endpoint of each plugin without a token which results in a 401 error:
```
[1] 2024-02-22T07:50:37.208Z backstage error Request failed with status 500 could not read http://localhost:7007/api/catalog/.well-known/backstage/permissions/metadata, 401 Unauthorized type=errorHandler stack=Error: could not read http://localhost:7007/api/catalog/.well-known/backstage/permissions/metadata, 401 Unauthorized
[1]     at _FetchUrlReader.readUrl (/backstage/app/node_modules/@janus-idp/backstage-plugin-rbac-backend/node_modules/@backstage/backend-common/src/reading/FetchUrlReader.ts:165:11)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at _PluginPermissionMetadataCollector.getPluginMetaData (/backstage/app/node_modules/@janus-idp/backstage-plugin-rbac-backend/src/service/plugin-endpoints.ts:98:26)
[1]     at _PluginPermissionMetadataCollector.getPluginPolicies (/backstage/app/node_modules/@janus-idp/backstage-plugin-rbac-backend/src/service/plugin-endpoints.ts:73:28)
[1]     at <anonymous> (/backstage/app/node_modules/@janus-idp/backstage-plugin-rbac-backend/src/service/policies-rest-api.ts:563:24)
```

In the source code, the token is not being used.
https://github.com/janus-idp/backstage-plugins/blob/49a5a70e47b00c743bad83372e3cd4e4a8d17bf2/plugins/rbac-backend/src/service/plugin-endpoints.ts#L98

I'm wondering whether it is a bug or something wrong with my setup.

Both backend and frontend plugins were installed as per the documentation. Here's my config for the permissions:
```yaml
permission:
  enabled: true
  rbac:
    admin:
      users:
        - name: group:default/my-group
      superUsers:
        - name: user:default/my-user
    pluginsWithPermission:
      - devtools
```

**Comment by PatAKnight** [comment]
Hello,

Thank you for submitting an issue. I don't believe that it is a bug as the `well-known` endpoint is not protected by any [permissions](https://github.com/backstage/backstage/blob/master/plugins/permission-node/src/integration/createPermissionIntegrationRouter.ts#L367) that I am aware of. In testing, I was able to not give my user any permissions and was still able to access the endpoint http://localhost:7007/api/catalog/.well-known/backstage/permissions/metadata directly. But I could always be wrong.

I am having some difficulty trying to reproduce your issue at the moment and have a few questions. What version of Backstage/RBAC backend/RBAC frontend are you using? Are there any additional errors that are present in the console? Were there any errors in the browser?

**Comment by boris154** [comment]
Hi @PatAKnight 

I think I found the problem. My setup includes API auth validation based on [this document](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md).

So any request to the API without a token, results in a 401 error.

I assume the auth middleware should allow access to the `well-known` endpoints. 
The other open is to add a token to the request.

WDYT ?

**Comment by PatAKnight** [comment]
Thank you for that documentation, I was able to reproduce the problem. 

You are correct, we do in fact need the token for the `well-known` endpoint and I would consider this a bug.

**Comment by cftad** [comment]
+1 For this - we're also experiencing the same problem when using S2S auth with RBAC [Slack Thread](https://janus-idp.slack.com/archives/C04EDTPJRK5/p1707157605366009).
