### ISSUE TITLE
Non-existent Dependency Versions Due to Workflow Timeout

### ISSUE THREAD

**Issue by schultzp2020** [janus-idp/backstage-plugins#1467]
**Description:**
Some plugins are currently referencing dependency versions that do not exist within the repository. This issue stemmed from a timeout in the release workflow. Consequently, the versions in `package.json` files were incremented without corresponding updates in npm. This situation particularly affects plugins reliant on shared dependencies, such as those depending on `@janus-idp/shared-react`.

**Workflow Details:**
- Original Workflow Timeout: [Link](https://github.com/janus-idp/backstage-plugins/actions/runs/8571877606/attempts/1)
- Subsequent Rerun Workflow: [Link](https://github.com/janus-idp/backstage-plugins/actions/runs/8571877606)

**Impact:**
This issue disrupts the functionality of plugins that depend on shared dependencies within the repository, causing an issue when running `yarn install`.

**Resolution:**
The root cause of the workflow timeout needs to be addressed to prevent similar issues in the future.

**Comment by nickboldt** [comment]
> Somehow we need a no op to bump all the plugin versions but the tool we use will automatically detect and not release no ops.

what if we turn off the "tool" temporarily, fix things, release what we need, and then turn the controls back on?

or, for a more permanent fix, can we tweak the tool to allow no-op version bumps? we'll need that going forward if we want to be able to release from 1.yy.x branches as in https://issues.redhat.com/browse/RHIDP-1720 and https://issues.redhat.com/browse/RHIDP-931

**Comment by nickboldt** [comment]
More detailed errors:

```
Couldn't find any versions for "@janus-idp/backstage-plugin-rbac-node" that matches "1.0.5"
Couldn't find any versions for "@janus-idp/shared-react" that matches "2.5.4"
```

Shorthand for doing a release:

1. [install & build](https://github.com/janus-idp/backstage-plugins/blob/main/.github/actions/build/action.yaml)
2. [release](https://github.com/janus-idp/backstage-plugins/blob/main/.github/workflows/push.yaml#L50-L55) 

```
# install & build
yarn --prefer-offline --frozen-lockfile
yarn build --filter=@janus-idp/* --concurrency=1

# release (push)
yarn config set registry https://registry.npmjs.org
npm config set registry https://registry.npmjs.org
npm config set workspaces-update false
yarn release --ignore-private-packages

**Comment by nickboldt** [comment]
Dgging into the failures, looks like timeouts:

```
2024-04-05T16:05:25.7295371Z [4:05:25 PM] [@janus-idp/backstage-plugin-rbac-node] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git push --tags https://x-access-token:[secure]@github.com/janus-idp/backstage-plugins HEAD:main
2024-04-05T16:05:25.7299831Z fatal: unable to access 'https://github.com/janus-idp/backstage-plugins/': Failed to connect to github.com port 443 after 133302 ms: Connection timed out
2024-04-05T16:05:25.7313878Z     at makeError (/home/runner/work/backstage-plugins/backstage-plugins/node_modules/execa/lib/error.js:60:11)
2024-04-05T16:05:25.7316213Z     at handlePromise (/home/runner/work/backstage-plugins/backstage-plugins/node_modules/execa/index.js:118:26)
2024-04-05T16:05:25.7318040Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-05T16:05:25.7320350Z     at async push (/home/runner/work/backstage-plugins/backstage-plugins/node_modules/@semantic-release/git/lib/git.js:51:3)
2024-04-05T16:05:25.7323227Z     at async module.exports (/home/runner/work/backstage-plugins/backstage-plugins/node_modules/@semantic-release/git/lib/prepare.js:69:5)
2024-04-05T16:05:25.7326178Z     at async prepare (/home/runner/work/backstage-plugins/backstage-plugins/node_modules/@semantic-release/git/index.js:28:3)
2024-04-05T16:05:25.7328871Z     at async validator (/home/runner/work/backstage-plugins/backstage-plugins/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
2024-04-05T16:05:25.7331555Z     at async /home/runner/work/backstage-plugins/backstage-plugins/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
2024-04-05T16:05:25.7333153Z     at async Promise.all (index 0)
2024-04-05T16:05:25.7334776Z     at async next (/home/runner/work/backstage-plugins/backstage-plugins/node_modules/p-reduce/index.js:16:18) {
2024-04-05T16:05:25.7337434Z   shortMessage: 'Command failed with exit code 128: git push --tags https://x-access-token:[secure]@github.com/janus-idp/backstage-plugins HEAD:main',
2024-04-05T16:05:25.7339956Z   command: 'git push --tags https://x-access-token:[secure]@github.com/janus-idp/backstage-plugins HEAD:main',
2024-04-05T16:05:25.7342235Z   escapedCommand: 'git push --tags "https://x-access-token:[secure]@github.com/janus-idp/backstage-plugins" "HEAD:main"',
2024-04-05T16:05:25.7343669Z   exitCode: 128,
2024-04-05T16:05:25.7344258Z   signal: undefined,
2024-04-05T16:05:25.7344921Z   signalDescription: undefined,
2024-04-05T16:05:25.7345647Z   stdout: '',
2024-04-05T16:05:25.7347620Z   stderr: "fatal: unable to access 'https://github.com/janus-idp/backstage-plugins/': Failed to connect to github.com port 443 after 133302 ms: Connection timed out",
2024-04-05T16:05:25.7349396Z   failed: true,
2024-04-05T16:05:25.7349966Z   timedOut: false,
2024-04-05T16:05:25.7350552Z   isCanceled: false,
2024-04-05T16:05:25.7351151Z   killed: false,
2024-04-05T16:05:25.7351810Z   pluginName: 'Inline plugin'
2024-04-05T16:05:25.7352472Z }
2024-04-05T16:05:25.7354855Z [multi-semantic-release]: Error: Command failed with exit code 128: git push --tags https://x-access-token:[secure]@github.com/janus-idp/backstage-plugins HEAD:main
2024-04-05T16:05:25.7358093Z fatal: unable to access 'https://github.com/janus-idp/backstage-plugins/': Failed to connect to github.com port 443 after 133302 ms: Connection timed out
```

-- https://pipelinesghubeus15.actions.githubusercontent.com/ebKQgoyPnXvHq3441lsPYuPjXKXGuQU3QPI6NQst2SLSVW3NT6/_apis/pipelines/1/runs/22072/signedlogcontent/10?urlExpires=2024-04-07T18%3A00%3A24.5955947Z&urlSigningMethod=HMACV1&urlSignature=U9Irza%2FNemy6KQC5p8%2BhQxgNxMgAT5kllV%2Fxx1x0lCM%3D (from https://github.com/janus-idp/backstage-plugins/actions/runs/8571877606/job/23493598212 )

**Comment by tumido** [comment]
> Or... can we figure out a way to recover w/o manual intervention?
> 
> * if timeout within action, wait 60s and try again a second time?
> * if action fails, wait 60s and automatically re-run failing steps?
 
Something like this can help with that:
https://github.com/marketplace/actions/retry-step

> Could we split this into more than 1 giant publishing step for 40 plugins? Eg., could we run the `yarn release` for each plugin, check if it succeeds, and then move to the next one? Would make parsing the log easier too...

You can't effectively do that if you have packages depending on another package within the repo. Or you can, but your workflow would need to determine which packages to release first. It's a whole graph of releases that you need to cascade through in the right order. 🤷 

```
shared library release -> common package release -> backend and frontend can be released.
```

**Comment by nickboldt** [comment]
CLosing this issue as it's not a problem anymore. Have moved the suggestion about https://github.com/marketplace/actions/retry-step to https://issues.redhat.com/browse/RHIDP-1720
