### ISSUE TITLE
[servicenow] Invalid create record request

### ISSUE THREAD

**Issue by viniciusfcf** [janus-idp/backstage-plugins#2011]
### Describe the bug

The create record action should include `Content-Type` header, and the value should be: `application/json, application/xml or text/xml`

Response error:
```
{"actor":{"actorId":"scaffolder-backend"},"errors":[{"message":"Invalid content-type. Supported request media types for this service are: [application/json, application/xml, text/xml]","name":"Error","stack":"Error: Invalid content-type. Supported request media types for this service are: plication/json, application/xml, text/xml]\n at Object.handler (/opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-scaffolder-backend-module-servicenow-dynamic-1.4.14/dist/cjs/index-54073476.cjs.js:703:15)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async NunjucksWorkflowRunner.executeStep (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-CDFi_apW.cjs.js:2805:9)\n at async NunjucksWorkflowRunner.execute (/ opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-CDFi_apW.cjs.js:2928:9)\n at async TaskWorker.runOneTask (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-CDFi_apW.cjs.js:3229:26)\n at async run (/opt/app-root/src/node_modules/p-queue/dist/index.js:163:29)"}],"eventName":"S caffolderTaskStepExecution","isAuditLog":true,"level":"error","message":"Step Snow 2 (id: snowCreate) of task 1143cf43-2a64-4b2b-b71b-55933512dfb0 failed","meta":{"isDryRun":false,"stepAction":"servicenow:now:table:createRecord","stepId":"snowCreate","stepName":"Snow 2","taskId":"1143cf43-2a64-4b2b-b71b-55933512dfb0","templateRef":"template:default/quarkus-web- template"},"plugin":"scaffolder","service":"backstage","stage":"completion","status":"failed","timestamp":"2024-08-06 01:22:51"} 
```

### Expected Behavior

create the record in service now

### What are the steps to reproduce this bug?

the correctly curl command it's 
```
curl "https://ven05429.service-now.com/api/now/table/u_pessoa" \
--request POST \
--header "Accept:application/json" \
--header "Content-Type:application/json" \
--data "{\"name\": \"Vinicius\"}" \
--user 'admin':'admin'
```

However if you remove the Content-Type the response will be:
```
{"error":{"message":"Invalid content-type. Supported request media types for this service are: [application/json, application/xml, text/xml]","detail":null},"status":"failure"}%
```

### Versions of software used and environment

RHDH version 1.2 and janus-idp-backstage-scaffolder-backend-module-servicenow-dynamic 1.4.14

**Comment by viniciusfcf** [comment]
Template file:

```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: snow-create-template
  title: Service Now template
  description: Create a record on table 'u_pessoa'
  tags:
    - snow
spec:
  owner: rhdh
  type: service
  steps:
    - id: snowCreate
      name: Snow 2
      action: servicenow:now:table:createRecord
      input:
        tableName: u_pessoa
        requestBody: '{"u_nome":"Vinicius","u_idade":"40"}'
  output:
    text:
    - title: More information
      content: |
        **Resultado** `${{ steps['snowCreate'].output.result }}`

```

![image](https://github.com/user-attachments/assets/4e78c882-2047-414a-bd71-6e4890f292bd)


Log file:

```
{"actor":{"actorId":"scaffolder-backend"},"errors":[{"message":"Invalid content-type. Supported request media types for this service are: [application/json, application/xml, text/xml]","name":"Error","stack":"Error: Invalid content-type. Supported request media types for this service are: [application/json, application/xml, text/xml]\n    at Object.handler (/opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-scaffolder-backend-module-servicenow-dynamic-1.4.14/dist/cjs/index-54073476.cjs.js:703:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async NunjucksWorkflowRunner.executeStep (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-CDFi_apW.cjs.js:2805:9)\n    at async NunjucksWorkflowRunner.execute (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-CDFi_apW.cjs.js:2928:9)\n    at async TaskWorker.runOneTask (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-CDFi_apW.cjs.js:3229:26)\n    at async run (/opt/app-root/src/node_modules/p-queue/dist/index.js:163:29)"}],"eventName":"ScaffolderTaskStepExecution","isAuditLog":true,"level":"error","message":"Step Snow 2 (id: snowCreate) of task 696cdc99-5a64-498f-8dc9-b59726d54225 failed","meta":{"isDryRun":false,"stepAction":"servicenow:now:table:createRecord","stepId":"snowCreate","stepName":"Snow 2","taskId":"696cdc99-5a64-498f-8dc9-b59726d54225","templateRef":"template:default/snow-create-template"},"plugin":"scaffolder","service":"backstage","stage":"completion","status":"failed","timestamp":"2024-08-12 14:04:57"}
{"actor":{"actorId":"scaffolder-backend"},"errors":[{"message":"Invalid content-type. Supported request media types for this service are: [application/json, application/xml, text/xml]","name":"Error"}],"eventName":"ScaffolderTaskExecution","isAuditLog":true,"level":"error","message":"Scaffolding task with taskId: 696cdc99-5a64-498f-8dc9-b59726d54225 failed","meta":{"taskId":"696cdc99-5a64-498f-8dc9-b59726d54225","taskParameters":{}},"plugin":"scaffolder","service":"backstage","stage":"completion","status":"failed","timestamp":"2024-08-12 14:04:57"}
{"level":"info","message":"127.0.0.1 - - [12/Aug/2024:14:04:58 +0000] \"GET /api/scaffolder/v2/tasks/696cdc99-5a64-498f-8dc9-b59726d54225/eventstream HTTP/1.1\" 200 - \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36\"","service":"rootHttpRouter","timestamp":"2024-08-12 14:04:58","type":"incomingRequest"}
{"actor":{"actorId":"user:default/user1","hostname":"backstage-backstage.apps.cluster-7qjtt.sandbox225.opentlc.com","ip":"127.0.0.1","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"},"eventName":"ScaffolderTaskStream","isAuditLog":true,"level":"info","message":"Event stream observing scaffolding task with taskId: 696cdc99-5a64-498f-8dc9-b59726d54225 was closed by user:default/user1","meta":{"taskId":"696cdc99-5a64-498f-8dc9-b59726d54225"},"plugin":"scaffolder","request":{"body":{},"method":"GET","params":{"taskId":"696cdc99-5a64-498f-8dc9-b59726d54225"},"query":{},"url":"/api/scaffolder/v2/tasks/696cdc99-5a64-498f-8dc9-b59726d54225/eventstream"},"service":"backstage","stage":"completion","status":"succeeded","timestamp":"2024-08-12 14:04:58"}
{"level":"info","message":"127.0.0.1 - - [12/Aug/2024:14:04:58 +0000] \"GET /static/282.cffe952a.chunk.js HTTP/1.1\" 200 - \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36\"","service":"rootHttpRouter","timestamp":"2024-08-12 14:04:58","type":"incomingRequest"}
```

**Comment by viniciusfcf** [comment]
After read the source code of the plugin I found the issue. To work the servicenow create record step should be like:

```
  steps:
    - id: snowCreate
      name: Snow Create Pessoa
      action: servicenow:now:table:createRecord
      input:
        tableName: u_pessoa
        requestBody: {
          name: 'Vinicius'
        }
```
