### ISSUE TITLE
backstage-plugin-keycloak-backend plugin is not working

### ISSUE THREAD

**Issue by paralika** [janus-idp/backstage-plugins#2102]
Hello, 

I am trying to setup @janus-idp/backstage-plugin-keycloak-backend/alpha plugin in my environment, however it is failing with the below error. 

[1] 2024-08-28T15:21:28.703Z catalog error Error while syncing Keycloak users and groups Request failed with status code 500 class=KeycloakOrgEntityProvider taskId=KeycloakOrgEntityProvider:default:refresh taskInstanceId=xxxxxxx-06d6-xxxx-90dd-14597c20fe11 name=Error stack=Error: Request failed with status code 500
[1]     at createError (/Users/vaibhav/Workspace/backstage/node_modules/@keycloak/keycloak-admin-client/node_modules/axios/lib/core/createError.js:16:15)
[1]     at settle (/Users/vaibhav/Workspace/backstage/node_modules/@keycloak/keycloak-admin-client/node_modules/axios/lib/core/settle.js:17:12)
[1]     at IncomingMessage.handleStreamEnd (/Users/vaibhav/Workspace/backstage/node_modules/@keycloak/keycloak-admin-client/node_modules/axios/lib/adapters/http.js:322:11)
[1]     at IncomingMessage.emit (node:events:529:35)
[1]     at endReadableNT (node:internal/streams/readable:1400:12)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) status=500
[1] 2024-08-28T15:21:28.705Z catalog debug task: KeycloakOrgEntityProvider:default:refresh will next occur around 2024-08-28T11:41:28.704-04:00 task=KeycloakOrgEntityProvider:default:refresh

I am following the configuration steps from(for new backend configuration) - https://janus-idp.io/plugins/keycloak/ 

I have verified keycloak client by querying api from command line, it is able to fetch users, but same not working with backstage. 

Can someone please help me with this?

**Comment by kim-tsao** [comment]
Hello @paralika , can you tell me what version of Keycloak you are using?

**Comment by paralika** [comment]
It was some connection issue, resolved by itself.
