### ISSUE TITLE
[backstage-plugin] getting error on yarn dev

### ISSUE THREAD

**Issue by invincibleJai** [janus-idp/backstage-plugins#276]
**Describe the bug**
on the backstage plugin am getting errors on the main branch

**To Reproduce**

1. Go to main in https://github.com/janus-idp/backstage-plugins (observed on latest commit dcf345f8f0ca27f85cb4bf158a1d223cb706bb60)
2. yarn install
3. yarn dev
4. See the below error and the app won't start properly

node --version
v16.17.1
yarn -v
1.22.0

```
yarn run v1.22.0
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[0] ⚠️   Some of the following packages may be outdated or have duplicate installations:
[0]
[0]           @backstage/plugin-catalog-backend, @backstage/plugin-catalog
[0]
[0] ⚠️   This can be resolved using the following command:
[0]
[0]           yarn backstage-cli versions:check --fix
[0]
[1] Build succeeded
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/jaivardhankumar/workspaces/backstage-plugins/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /catalog
[1] Loaded config from app-config.yaml
[1] 2023-04-20T08:09:25.398Z backstage info Found 2 new secrets in config that will be redacted
[1] 2023-04-20T08:09:25.416Z backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucketCloud{host=bitbucket.org,authed=false},github{host=github.com,authed=false},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaws.com,authed=false},fetch{}
[1] 2023-04-20T08:09:25.452Z catalog info Performing database migration type=plugin
[1] Backend failed to start up Error: Could not locate the bindings file. Tried:
[1]  → /Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/build/better_sqlite3.node
[1]  → /Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
[1]  → /Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/build/Release/better_sqlite3.node
[1]  → /Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
[1]  → /Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/Debug/better_sqlite3.node
[1]  → /Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/out/Release/better_sqlite3.node
[1]  → /Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/Release/better_sqlite3.node
[1]  → /Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/build/default/better_sqlite3.node
[1]  → /Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/compiled/16.17.1/darwin/x64/better_sqlite3.node
[1]  → /Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
[1]  → /Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
[1]  → /Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
[1]  → /Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/lib/binding/node-v93-darwin-x64/better_sqlite3.node
[1]     at bindings (/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/bindings/bindings.js:126:9)
[1]     at new Database (/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/lib/database.js:48:64)
[1]     at Client_BetterSQLite3.acquireRawConnection (/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/knex/lib/dialects/better-sqlite3/index.js:12:12)
[1]     at create (/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/knex/lib/client.js:254:39) {
[1]   tries: [
[1]     '/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/build/better_sqlite3.node',
[1]     '/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/build/Debug/better_sqlite3.node',
[1]     '/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/build/Release/better_sqlite3.node',
[1]     '/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/out/Debug/better_sqlite3.node',
[1]     '/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/Debug/better_sqlite3.node',
[1]     '/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/out/Release/better_sqlite3.node',
[1]     '/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/Release/better_sqlite3.node',
[1]     '/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/build/default/better_sqlite3.node',
[1]     '/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/compiled/16.17.1/darwin/x64/better_sqlite3.node',
[1]     '/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node',
[1]     '/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node',
[1]     '/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node',
[1]     '/Users/jaivardhankumar/workspaces/backstage-plugins/node_modules/better-sqlite3/lib/binding/node-v93-darwin-x64/better_sqlite3.node'
[1]   ]
[1] }
[0] webpack compiled successfully
```

**Expected behavior**
Shouldn't get any errors and the app should start

**Screenshots**

**Additional context**

**Comment by invincibleJai** [comment]
I removed node_modules and did a fresh install and this seems to help. Thus closing it.
