### ISSUE TITLE
3scale-backend backstage plugin error

### ISSUE THREAD

**Issue by sgutierr** [janus-idp/backstage-plugins#453]
I bump into an error (fetch is not defined) when run the 3scale-backend plugin, this is the log: 

[1] 2023-06-14T05:12:06.400Z catalog info Discovering ApiEntities from 3scale https://3scale-admin.apps.ocp4.eu/ type=plugin target=ThreeScaleApiEntityProvider:dev
[1] 2023-06-14T05:12:06.401Z catalog error fetch is not defined type=plugin target=ThreeScaleApiEntityProvider:dev stack=ReferenceError: fetch is not defined
[1]     at listServices (/home/sgutierr/development/3scaleIntegration/emeassa/node_modules/@janus-idp/backstage-plugin-3scale-backend/dist/index.cjs.js:9:3)
[1]     at _ThreeScaleApiEntityProvider.run (/home/sgutierr/development/3scaleIntegration/emeassa/node_modules/@janus-idp/backstage-plugin-3scale-backend/dist/index.cjs.js:131:24)
[1]     at TaskWorker.fn (/home/sgutierr/development/3scaleIntegration/emeassa/node_modules/@janus-idp/backstage-plugin-3scale-backend/dist/index.cjs.js:105:24)
[1]     at TaskWorker.runOnce (/home/sgutierr/development/3scaleIntegration/emeassa/node_modules/@backstage/backend-tasks/dist/index.cjs.js:360:18).

We found a work around, adding " var fetch = require('node-fetch'); "  in this file ../node_modules/@janus-idp/backstage-plugin-3scale-backend/dist/index.cjs.js and worked perfect.

_'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
**var fetch = require('node-fetch');**
var catalogModel = require('@backstage/catalog-model');
var backendTasks = require('@backstage/backend-tasks');_
.........

**Comment by fmenesesg** [comment]
Hi, @sgutierr , this is related to the node version on your environment, on node version 16 node-fetch was required, and on version 18 no extra packages are required. Can you please try to use node version 18 and let us know the result.

**Comment by sgutierr** [comment]
Hi @fmenesesg , upgrading my node version to 18 works properly, thank you for your help!
