### ISSUE TITLE
[Keycloak Plugin] Catalog fails to read from Keycloak during deployment

### ISSUE THREAD

**Issue by PatAKnight** [janus-idp/backstage-plugins#949]
### Describe the bug

When using the Keycloak plugin as a dynamic plugin with RHDH, I encounter the following error:

```
2023-11-16T19:17:59.256Z catalog error KcAdminClient is not a constructor type=plugin class=KeycloakOrgEntityProvider taskId=KeycloakOrgEntityProvider:default:refresh taskInstanceId=32e953ad-9e50-41d0-ab16-eb87e0ba6cc5 stack=TypeError: KcAdminClient is not a constructor
at KeycloakOrgEntityProvider.read (/opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-plugin-keycloak-backend-dynamic-1.7.1/dist/cjs/KeycloakOrgEntityProvider-9b3ad730.cjs.js:326:27)
at fn (/opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-plugin-keycloak-backend-dynamic-1.7.1/dist/cjs/KeycloakOrgEntityProvider-9b3ad730.cjs.js:374:24)
at TaskWorker.fn (/opt/app-root/src/node_modules/@backstage/backend-tasks/dist/index.cjs.js:599:15)
at TaskWorker.runOnce (/opt/app-root/src/node_modules/@backstage/backend-tasks/dist/index.cjs.js:350:18)
at async /opt/app-root/src/node_modules/@backstage/backend-tasks/dist/index.cjs.js:298:31
```

This results in the prevention of users and groups from being read into RHDH.

### Expected Behavior

The Keycloak plugin should function without failure and properly read in users and groups.

### What are the steps to reproduce this bug?

1. Deploy RHDH using the Helm Chart
2. Add an app config file for Keycloak
3. Upgrade RHDH Helm Chart enabling the Keycloak Backend Plugin

**Comment by davidfestal** [comment]
The right fix for this issue should be https://github.com/janus-idp/backstage-plugins/pull/971.
However to avoid any disruption risk, this PR should only be merged after the showcase `1.0.x` branch code freeze.
