### ISSUE TITLE
Impossible to load the ServiceNow action as a dynamic plugin

### ISSUE THREAD

**Issue by davidfestal** [janus-idp/backstage-plugins#976]
We cannot currently install the servicenow custom action.

```
[2m2023-11-27T22:11:55.913Z[22m [34mbackstage[39m [31merror[39m an error occured while loading dynamic backend plugin '@janus-idp/backstage-scaffolder-backend-module-servicenow-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-scaffolder-backend-module-servicenow-dynamic-1.2.1' require() of ES Module /opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-scaffolder-backend-module-servicenow-dynamic-1.2.1/node_modules/node-fetch/src/index.js from /opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-scaffolder-backend-module-servicenow-dynamic-1.2.1/dist/index.cjs.js not supported.
Instead change the require of index.js in /opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-scaffolder-backend-module-servicenow-dynamic-1.2.1/dist/index.cjs.js to a dynamic import() which is available in all CommonJS modules. [36mcode[39m=ERR_REQUIRE_ESM [36mstack[39m=Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-scaffolder-backend-module-servicenow-dynamic-1.2.1/node_modules/node-fetch/src/index.js from /opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-scaffolder-backend-module-servicenow-dynamic-1.2.1/dist/index.cjs.js not supported.
Instead change the require of index.js in /opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-scaffolder-backend-module-servicenow-dynamic-1.2.1/dist/index.cjs.js to a dynamic import() which is available in all CommonJS modules.
at Object.<anonymous> (/opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-scaffolder-backend-module-servicenow-dynamic-1.2.1/dist/index.cjs.js:9:13)
at /opt/app-root/src/packages/backend/dist/index.cjs.js:639:116
at async CommonJSModuleLoader.load (/opt/app-root/src/packages/backend/dist/index.cjs.js:639:12)
at async PluginManager.loadBackendPlugin (/opt/app-root/src/node_modules/@backstage/backend-plugin-manager/dist/index.cjs.js:415:42)
at async PluginManager.loadPlugins (/opt/app-root/src/node_modules/@backstage/backend-plugin-manager/dist/index.cjs.js:394:24)
at async PluginManager.fromConfig (/opt/app-root/src/node_modules/@backstage/backend-plugin-manager/dist/index.cjs.js:378:29)
at async main (/opt/app-root/src/packages/backend/dist/index.cjs.js:712:25) 
```

**Comment by davidfestal** [comment]
According to https://bobbyhadz.com/blog/javascript-error-err-require-esm-require-of-es-module-not-supported#node-fetch-error-err_require_esm-require-of-es-module-not-supported, we should not have upgraded from `2.7.0` to `3.3.2`.
It was done in commit https://github.com/janus-idp/backstage-plugins/commit/060af8fcd5baf5513b1fc430cf54ddb3c012e8ef, during the upgrade to Backstage 1.19.0, but when looking in the current upstream backstage, it seems that they are still using the `2.6.7` version (not higher than that).
